services:
  web:
    build: .
    image: localhost/whatever_web_image:latest
    container_name: whatever_web
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./:/var/www/html
      - ./certs:/etc/apache2/certs
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html